import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
// import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

import store from "@/store/index";
import { Provider } from "react-redux";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Provider store={store}>
        <TooltipProvider>
          <html lang="en">
            <body className={`${font.className} antialiased bg-white`}>
              {/* <Toaster /> */}
              {children}
            </body>
          </html>
        </TooltipProvider>
      </Provider>
    </ClerkProvider>
  );
}
